//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingCart.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.POLineItems = new HashSet<POLineItem>();
        }
    
        public int Id { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPinCode { get; set; }
        public string EmailID { get; set; }
        public string PrimaryContactNo { get; set; }
        public string AlternateContactNo { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingPinCode { get; set; }
        public string ShippingPrimaryContactNo { get; set; }
        public string ShippingAlternateContactNo { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Cart Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLineItem> POLineItems { get; set; }
    }
}
